### ISSUE TITLE
I think it should be hard, not heard

### ISSUE THREAD

**Issue by Multimegamander** [ApacheThunder/ChaosGlitchMod#1]
but you're daddy thunder, so idk what's a typo for you

**Comment by ApacheThunder** [comment]
lol Thanks for pointing that out. Fixed it. Plan to update the mod again sometime soon. The 2.1.9 update removed an unused room prefab I use for my secret floor so as a result users of 2.1.9 won't be able to play the floor. I fixed it on my side by recreating the room prefab in code as I also happened to figure out how to create all new rooms in code without having to rely on existing room prefabs like my previous modded rooms I used. :D

As for my typos, those happen pretty regularly for me now a days. Combination of bad keyboard and be being a bit dyslexic typing. No so much dyslexic in reading or speaking. Just on the keyboard. Kinda weird. Happens mostly when I go back to revise a sentence/paragraph if I find something I need to expand on or explain differently. Sometimes I leave fragments of an old sentence in or just plain get letters mixed up when spelling a word. :P

One reason why I've done well in making code for this game. Mostly thanks to Visual Studio for pointing out mistakes for me in most cases so I don't have this problem when coding thankfully. The same can't be said for my DSI/3DS coding projects. Those I coded in Notepad/Notepad++ so was on my own when it came to finding errors in the code/syntax issues/etc. I had to rely on compile errors to find the problems that may crop up in those projects. 

Anyways I've corrected the error in the title so I'll close the issue. The main readme.md will be changed in the next commit too so if there's any mistakes there, they should be corrected when I get around to updating that. :P
